spring:
  application:
    name: MEOGO_Backend

  threads:
    virtual:
      enabled: true

  main:
    keep-alive: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DB}
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  exp: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}
